Vagrant.configure(2) do |config|
config.vm.box = "box-cutter/ubuntu1404-desktop"
config.vm.provider "virtualbox" do |vb|
vb.gui = true
vb.memory = "2048"
end
config.vm.provision "shell", inline: <<-SHELL

#Update the Ubuntu system
sudo apt-get update

#Install Java 1.7
sudo apt-get -y install openjdk-7-jdk

SHELL
end
